= Eye Toolbox Overview
:showtitle:
:sectnums:
:revdate: 2019-03-25

== Overview
There are two general categories of eye sensors on the market today, differentiated by the wavelength of light used to take an image of the iris. It is expected that a sensor uses one or the other--but not both--types of light when taking the image of the iris, though using both is not a barrier to testing. While there are also sensors that image the retina instead of the iris, this is not known to be used outside of fixed installations at this point and so are not included in the toolbox at this time.

Evaluating eye sensors that rely on near-Infrared (NIR) or Infrared (IR) requires the use of a camera that can take pictures using these wavelengths. Some mobile devices may support (or come close to supporting) this in a low-light mode. There are cameras on the market which explicitly support night modes that can take images using the proper wavelengths for these types of sensors.

== Eye Presentation Attacks
All attacks are based on using a digital source directly, not a printed photo that would then be scanned and printed again.

=== Visible Light Attacks

.Visible Light Attacks
[%header,cols=".^1,.^3,.^6"]
|===

|No.
|Source
|Description

|1
|Mobile Device Camera Image
|The target has taken a picture using the TOE's main camera and uploaded it to SNS/internet where it can be readily found and used as the basis of the PAI.

|2
|High Quality Camera Image
|The target has a high quality facial picture uploaded to SNS/internet where it can be readily found and used as the basis of the PAI.

|3
|Mobile Device Video
|The target has a low quality (e.g., 480p) video of their face taken and posted to SNS/internet where it can be readily found and used as the basis of the PAI.

|4
|High Quality Video
|The target has a high quality (e.g., 4K) video of their face taken and posted to SNS/internet where it can be readily found and used as the basis of the PAI.

|===

=== Near-Infrared (NIR) or Infrared (IR) Light Attacks

.NIR/IR Light Attacks
[%header,cols=".^1,.^3,.^6"]
|===

|No.
|Source
|Description

|1
|Mobile Device Camera Night Image
|The target has taken a picture using the TOE's main camera using low light/night settings.

|2
|High Quality Camera Night Image
|The target has a picture taken specifically in night mode (this may be forced).

|===

== Eye Presentation Attack Detection
Images captured by the TOE of the eye artefacts may visually look very similar to the images captured from a real human, however, they are not exactly the same. For example, printed or displayed images on paper or screens reflect light in different ways because humans are complex non-rigid 3D objects, whereas photos and screens can be seen as planar rigid objects. In addition, artefacts may contain moiré patterns that are an undesired aliasing produced during various image display and acquisition processes. The TOE can detect such differences between images taken from humans and artefacts to detect and prevent  presentation attacks.

NIR/IR images are created from aspects that are hidden from the visible light spectrum, but may have similar properties to visible light images when creating artefacts. These images may also contain moiré patterns that are an undesired aliasing produced during various image display and acquisition processes.

== Common Test Protocol
Eye PAD testing can be done in a variety of ways. The evaluator may use different types of cameras under different illuminations to capture eye images of test users to create artefacts. The evaluator may also present these artefacts under different conditions. It’s not possible to cover all such test scenarios. This toolbox defines a common test protocol to maintain consistency among different PAD testing environments. The evaluator shall follow the test protocols described below, in addition to guidance provided in Toolbox Overview, to conduct the PAD testing.

The tools and media for the creation of artefacts are defined for all tests in the link:EYE_Toolbox_Inventory.adoc[Eye Toolbox Inventory]. Each attack specifies which tools and media are to be used in the creation of artefacts for that test.

=== Image Recommendations

Note that when tests require the use of the contact lenses, the printed image of the iris shall match the diameter of the contact lens for proper overlay.

=== Enrolment Preparation - All Artefacts

. Enrolment
.. The evaluator shall enable eye unlock and enroll the test users following instructions provided by the AGD guidance (e.g., test users should not wear glasses during the enrolment if the guidance instructs not to do so).
.. The evaluator shall enroll test users’ eyes under the controlled environment where the background of the scene is uniform, the light in the room is switched on, and the window blinds are down (i.e., direct external lighting is blocked). 

=== Visible Light - Photos and Video
[start=2]
. Eye image capture
.. The evaluator shall capture eye images immediately after enrolment under identical conditions to reduce the possibility that the artefacts are rejected because of a difference in illumination, background scene, or expression.
.. The evaluator shall capture test users’ eye images with normal and high quality cameras for printed and digital photo attack. The evaluator shall also record video of the user's face (with clear view of the eyes) for ten seconds for reply video attack.

. Artefact creation
.. The evaluator shall print eye images for printed photo attacks, display them on a screen for digital photo attacks, and replay them on a screen for replay video attacks. The size of face images on artefacts shall be same as the test user’s face (to achieve the correct size for the eye).

. Artefact presentation
.. The evaluator shall present artefacts to the TOE under the identical controlled environment used during enrolment.
.. The evaluator shall adjust the distance between artefacts and the TOE so that the TOE can’t see the edge of artefacts.
.. The evaluator shall present artefacts in a way to minimize reflection from ambient lighting.
.. The evaluator shall present artefacts by hand for printed and digital photo attacks, introducing some noticeable motion, and by tripod for replay video attacks.

=== NIR/IR Light - Photos
[start=2]
. Eye image capture
.. The evaluator shall capture eye images immediately after the enrolment of test users. The conditions for capture should be as close as possible to the enrolment conditions, but must be balanced with the requirements of the camera.
+
For mobile device image,s this means taking the picture in low light, which may not be the best given the smallest amount of iris that will be shown.
+
For the camera with a night mode, this feature must be activated, preferably during daylight to get the best results.

.. The evaluator shall capture test users’ eye images with normal and high quality cameras for printed photo attacks.

. Artefact creation
.. The evaluator shall print eye images for printed photo attacks. Size of face images on artefacts shall be same as the test user’s face (to achieve the correct size for the eye).

. Artefact presentation
.. The evaluator shall present artefacts to the TOE under the identical controlled environment as used during enrolment.
.. The evaluator shall adjust the distance between artefacts and the TOE so that the TOE can’t see the edge of artefacts.
.. The evaluator shall present artefacts in a way to minimize the reflection from ambient lighting.
.. The evaluator shall present artefacts by hand for printed photo attack to introduce some noticeable motion.

== Requirements for Tools
The evaluator needs to use several tools (e.g., cameras, screens, printers, and media), that meet the specifications listed below, since these specifications impact the clarity or sharpness of eye artefacts. For example, the quality of digital photos depends on the screen resolution. If the screen is 4K (i.e., a horizontal screen resolution in the order of 4,000 pixels), it can provide the finest clarity and detail of the eye image.

This toolbox defines two level of tools--normal and high quality--to cover variety of tools to conduct the PAD testing efficiently. Not all tools have both levels.

Normal quality tools are inexpensive and can be used by novices to capture and upload images to social media. An attacker may also create eye artefacts with such uploaded images without difficulty. Detailed attack methods using uploaded images have been published on the Internet, so the evaluator shall try this type of artefact first. 

High quality tools have better performance (e.g., higher resolution) than normal quality tools.  Such tools should be the latest available (i.e., released at least within one year from the date of PAD testing, or as recent as possible depending on the type of device). Those tools may be expensive, but can be rented at an affordable cost. The reason why such tools should be used is that the PAD algorithm may show good rejection performance for artefacts used to train the algorithm, but reduced rejection performance for artefacts the algorithm has never seen before. Attackers may additionally create high-quality artifacts to maximize the chance of successful attacks. 

The evaluator shall create such artefacts that with the highest likelihood of bypassing the PAD using the latest tools.

== Test Items
The evaluator shall create artefacts defined in all test items listed in the link:EYE_Toolbox_Verification_List.adoc[Eye Toolbox Verification List]. The Eye Toolbox Verification List specifies the species types that must be created based on the type of biometric sensor.

PAD Toolbox Overview defines required number of attempts for the independent testing and maximum timeframe for both independent and penetration testing.

== Pass/Fail Criteria
If Pass/Fail Criteria is defined in the test items, then the evaluator shall follow them. Otherwise, the evaluator shall follow criteria defined in BIOSD and PAD Toolbox Overview.

== Reference Information 
The Eye Toolbox was created based on research papers listed in both the Face and Eye Toolbox References. The evaluator should read them before conducting the PAD testing because they include more detailed information about PAD test methods.
