= Eye Toolbox Inventory
:showtitle:
:revdate: 2026-03-31

This document contains the inventory of tools and materials that are used in the context of the toolbox.

== Overview
This document specifies requirements for tools that are used to create eye image artefacts. There are two types of tools and media: Type 1 and Type 2. Not all tools or media may have both types. Generally, the evaluator shall create "normal" quality eye artefacts using Type 1 tools and "high" quality face artefacts with Type 2 tools. The requirements for each tool are specified in the following tables.

The evaluator may use any tools and media to create eye artefacts as long as they meet requirements specified below. The evaluator may use any available services (e.g., rental services) to prepare any tools in cost effective way.

The evaluator may need to use other tools that are not specified here. 

Some examples:

* The evaluator may connect the camera to a TV directly to replay the eye image on a 4K screen
* A camera video file could be imported to a PC from a camera and played directly from a 4K PC screen.
+
In such cases, the evaluator may use any PC and viewer software, however, the evaluator shall visually check the final image on the screen. If the evaluator sees any problem (e.g., choppy video playback because of an underpowered CPU), the evaluator shall replace the tools with an alternative that does not exhibit the problem. 

== Tools Inventory
.Tool Requirements
[cols=".^1,.^1,3,3",options="header"]
|===
|ID
|Category
|Type 1
|Type 2


|EY1-T.1
|Camera
a|Mobile device camera

* A mobile device where the https://www.dxomark.com/smartphones/[Smartphone Camera score] is at least 130.

* The evaluator shall not use the same mobile device on which the TOE is installed.
a|Camera

* A camera where the sensor meets the following measures (which can be found at https://www.dxomark.com/camera-sensors/)
** Native ISO: &#8804; 100
** Dynamic range at ISO 100: &#8805; 13 EV
** Color depth at ISO 100: &#8805; 25.0 bits
** Pixel count (in megapixels): &#8805; 30 MP
** SNR 18% (SNR at 18% greyscale) at ISO 100: &#8805; 42 dB
* A camera lens with the following https://www.dxomark.com/camera-lenses/[rankings]:
** Overall score: &#8805; 30
** Sharpness score: &#8805; 20

|EY1-T.2
|Night-mode camera
|T.1a camera in night/low light mode (could be mobile device or dSLR)
|Camera with explicit night mode/NIR functionality

|EY1-T.3
|Photo Inkjet Printer or Service
2+a|Either a photo-capable inkjet printer or a professional service may be used for printing the photos. Printer quality should meet quality expected from a service.

For an Inkjet printer:

* A dedicated photo printer (not an all-in-one that also prints photos) no more than 5 years old.
** The printer's resolution must be able to print at least 2400x1200 DPI.
** OEM pigmented inks must be used.
** Use "High" print quality settings.

For all prints:

* Test user's face shall be printed on paper in full scale.
* The evaluaor shall maintain the original aspect ratio during printing to avoid distortion of the face image.
* The evaluator shall crop the face from the printed photo, as some devices might detect the non-matching background.
* The evaluator shall refer to publicly available information to select the best one (e.g., quality comparison report for professional print services). 
* The evaluator shall follow recommendations from the printer guidance or professional print service (e.g., recommended image file size) to get the highest quality of photo print. 

|===


== Materials Inventory

.Materials Requirements
[cols=".^1,.^1,3,3",options="header"]
|===

|ID
|Category
|Type 1
|Type 2 

|EY1-M.1
|Paper
a|Matte photo paper 

* Paper shall be wide enough to include a test user's face at full scale.

a|Paper recommend by professional print service

* Paper shall be wide enough to include a test user's face at full scale.
* The evaluator shall select the best paper type to print the best quality face images.

|EY1-M.2
|Screen              
a|Mobile device screen

* The evaluator shall use the same mobile device used for capturing test user's eye.
* Test user's eye shall be displayed or replayed on the screen in full scale.
a|High resolution screen

* The evaluator shall use the highest resolution screen that was released within the previous 1 year period starting from the date of testing.
* Test user's face (eye) shall be displayed or replayed on the screen in full scale.

|EY1-M.3
|Eye Mimicry
|Standard, non-colored contact lens with low prescription
|A fake eye (e.g., doll eye) that is open to the back with a clear opening for the iris (could be a hole or clear material)

|===
