= Attack L1-Eye EY1-05-xx

== Attack type
Eye, IR/NIR printed photo attack with contact lens

=== Total Number of Species
This attack has *2* species to be tested.

== Overview
The evaluator captures and prints a target user's eye on paper, then adds more materials to mimic an eye, and presents it to the TOE.

== Input
Target user's eyes are open and iris is mostly non-occluded.

== Tools
*Contact Lens*

* EY1-T.2, Type 2
* EY1-T.3
* EY1-M.1, Type 1
* EY1-M.3, Type 1

== Recipe
. The evaluator shall capture the eye image and print it on a paper. 
. The evaluator shall refer to publicly available information to change default setting of the camera (e.g., image resolution) and printer (e.g., output resolution) to create clearer eye artefacts.
. The evaluator shall take at least three photos and select the best one to create each eye artefact.
. The evaluator shall prepare the artefact with the specified materials.

=== Contact Lens Recipe
Using the contact lens requires that the eye photo be printed to scale so the contact properly covers the entire iris, as it would when worn by a person. 

== Variations
=== Variation 1 (L1-Eye EY1-05-02)
*Doll Eye*

* EY1-T.2, Type 2
* EY1-T.3
* EY1-M.1, Type 1
* EY1-M.3, Type 2

=== Doll Eye Recipe
The chosen artefact photo will be placed inside a fake eye (e.g., doll eye or similar sphere) and presented as close as possible to bend inside the surface. The evaluator should take care to minimize folding that may occur in the image.

== Prerequisite
The evaluator shall enrol test users first as described in the Eye Toolbox Overview. If the ST covers multiple configurations for eye unlock, the same test shall be performed for all configurations.

== Presentation
The evaluator shall present a artefact by hand as described in the Eye Toolbox Overview.

== Penetration Testing and Attack Potential Rating Suggestions
=== Penetration Testing Suggestion
The evaluator should consider changing the following factors for penetration testing.

* Configuration of tool
+
The evaluator may, for example, change color effects of the camera to change the quality of the images. Such change may affect the texture of artefacts that may lead to false acceptance. 
* Presentation method
+ 
As described in BIOSD, the evaluator may change the distance between the artefact and the TOE. In addition to that, the evaluator may deliberately warp a printed photo, trying to simulate facial motion (Warped photo attack).

=== Attack Potential Rating Suggestion
The attack potential that is required to build the artefacts are summarized in the following table. See BIOSD Section 9 for more information about how to calculate the attack potential. 

Attack Potential values are shown in <<calculatedtable>>. Attack Potential values for Identification account for the time, expertise, etc. required to make the printed photo described in this attack. Attack potential for Exploitation corresponds to the effort to attack the TOE using the PAI in the actual environment. <<calculatedtable>> shows the final attack potential to rate the vulnerabilities and TOE resistance.

*All Variations*

.Calculated Attack Potential Eye attack EY1-05-xx
[[calculatedtable]]
[cols=".^2,.^2,^.^1,.^2,^.^1,^.^1",options="header",]
|===
|Factor 
|Identification Value
|Score
|Exploitation Value
|Score
|Total

|*Elapsed Time*
|<= one day
|1
|<= one hour
|0
|1

|*Expertise*
|Layman
|0
|Proficient
|2
|2
 
|*Knowledge of TOE*    
|Public
|0 
|Public
|0 
|0

|*Equipment*
|Standard
|0 
|Standard
|0
|0

a|*Window of Opportunity*

*(Access to Biometric Characteristics)* 
|N/A
|
|Opportunistic Easy
|2
|2

a|*Window of Opportunity*

*(Access to TOE)* 
|Easy
|0
|Moderate
|4
|4

|*Degree of Scrutiny*
|None
|0 
|None
|0
|0

6+^.^|Total Attack Potential = 9 < Basic Attack Potential

|===

== Pass Criteria
There are no additional criteria other than defined in BIOSD and PAD Toolbox Overview.
