= Attack L1-Eye EY1-03-xx

== Attack type
Eye, replay video attack

=== Total Number of Species
This attack has *2* species to be tested.

== Overview
The evaluator records and replays a target user's eyes on a screen and presents it to the TOE.

== Input
Target user's eyes are open and iris is mostly non-occluded.

== Tools
*Normal Quality*

* EY1-T.1, Type 1
* EY1-M.2, Type 1

== Recipe
. The evaluator shall capture a 10 second video of the eyes and display it on a screen. 

. The evaluator shall refer to publicly available information to change default setting of the camera (e.g., video resolution) to create clearer eye artefacts.

. The evaluator shall take at least three videos and select the best one to create each eye artefact.

== Variations
=== Variation 1 (L1-Eye EY1-03-02)
*High Quality*

* EY1-T.1, Type 2
* EY1-M.2, Type 2

== Prerequisite
The evaluator shall enrol test users first as described in the Eye Toolbox Overview. If the ST covers multiple configurations for eye unlock, the same test shall be performed for all configurations.

== Presentation
The evaluator shall present the screen by hand as described in the Eye Toolbox Overview.

== Penetration Testing and Attack Potential Rating Suggestions
=== Penetration Testing Suggestion
The evaluator should consider changing the following factors for penetration testing.

* Configuration of tool
+
The evaluator may, for example, change color effects of the camera to change the quality of the images. Such change may affect the texture of artefacts that may lead to false acceptance. 
* Presentation method
+ 
As described in BIOSD, the evaluator may change the distance between the artefact and the TOE.

=== Attack Potential Rating Suggestion
The attack potential that is required to build the artefacts are summarized in the following table. See BIOSD Section 9 for more information about how to calculate the attack potential. 

Attack Potential values are shown in <<calculatedtable>>. Attack Potential values for Identification account for the time, expertise, etc. required to make the printed photo described in this attack. Attack potential for Exploitation corresponds to the effort to attack the TOE using the PAI in the actual environment. <<calculatedtable>> shows the final attack potential to rate the vulnerabilities and TOE resistance.

*All Variations*

.Calculated Attack Potential Eye attack EY1-03-xx
[[calculatedtable]]
[cols=".^2,.^2,^.^1,.^2,^.^1,^.^1",options="header",]
|===
|Factor 
|Identification Value
|Score
|Exploitation Value
|Score
|Total

|*Elapsed Time*
|<= one day
|1
|<= one hour
|0
|1

|*Expertise*
|Layman
|0
|Layman
|0
|0
 
|*Knowledge of TOE*    
|Public
|0 
|Public
|0 
|0

|*Equipment*
|Standard
|0 
|Standard
|0
|0

a|*Window of Opportunity*

*(Access to Biometric Characteristics)* 
|N/A
|
|Opportunistic Easy
|2
|2

a|*Window of Opportunity*

*(Access to TOE)* 
|Easy
|0
|Moderate
|4
|4

|*Degree of Scrutiny*
|None
|0 
|None
|0
|0

6+^.^|Total Attack Potential = 7 < Basic Attack Potential

|===

== Pass Criteria
There are no additional criteria other than defined in BIOSD and PAD Toolbox Overview.